metadata:
  name: 퓨전 개발자 101
  short_name: fds
  description: >-
    This is the website for fusion devs who use Microsoft Power Platform for
    their work.
  language: ko
  url: 'https://study.fusiondev.kr'
  pathPrefix: /
  gaTrackingId: null
  favicon: /assets/favicon.png
  themeColor: '#0066cc'
header:
  enabled: true
  logo: /assets/logo.png
  links: []
sidebar:
  ignoreIndex: false
  forcedNavOrder: []
  expanded: []
  groups:
  - order: 1000
    path: /power-platform
    title: ":rocket: 파워 플랫폼"
  - order: 2000
    path: /spo
    title: ":rainbow: 셰어포인트 온라인"
  - order: 3000
    path: /d365
    title: ":fuelpump: 다이나믹스 365"
  - order: 4000
    path: /certs
    title: ":scroll: 자격증 준비"
  links: []
  poweredBy: {}
  enabled: true
pwa:
  enabled: true
  manifest:
    icon: /assets/logo.png
    display: minimal-ui
    crossOrigin: anonymous
features:
  editOnRepo:
    editable: true
    location: 'https://github.com/fusiondevkr/blog'
    type: github
  toc:
    show: true
    depth: 3
  search:
    enabled: true
    engine: localsearch
    localSearchEngine: balance
    excerptSize: 10000
    # indexName: docs
    startComponent: input
    showStats: true
    pagination:
      enabled: true
  rss:
    enabled: false
    showIcon: true
    copyright: ''
    categories: []
    matchRegex: ^/
    outputPath: /rss.xml
  darkMode:
    enabled: true
    default: false
social:
  facebook: 'https://facebook.com/groups/fusiondevkr'
  github: 'https://github.com/fusiondevkr'
  twitter: 'https://twitter.com/fusiondevkr'
  youtube: 'https://youtube.com/fusiondevkr'
search:
  enabled: true
  startComponent: input
  placeholder: Search...
  pagination:
    enabled: true
