metadata:
  name: 퓨전 개발자 101
  short_name: fds
  description: >-
    This is the website for fusion devs who use Microsoft Power Platform for
    their work.
  language: ko
  url: 'https://study.fusiondev.kr'
  pathPrefix: /
  gaTrackingId: null
  favicon: /assets/favicon.png
  themeColor: '#0066cc'
header:
  enabled: true
  logo: /assets/logo.png
  links: []
sidebar:
  ignoreIndex: false
  forcedNavOrder: []
  expanded: []
  groups:
  - order: 1
    path: /pp
    title: ":rocket: 파워 플랫폼"
  - order: 2
    path: /pas
    title: ":rocket: 파워 앱"
  - order: 3
    path: /pau
    title: ":rocket: 파워 오토메이트"
  - order: 4
    path: /pva
    title: ":rocket: 파워 버추얼 에이전트"
  - order: 5
    path: /pbi
    title: ":rocket: 파워 BI"
  - order: 6
    path: /m365
    title: ":computer: 마이크로소프트 365"
  - order: 7
    path: /spo
    title: ":rainbow: 셰어포인트 온라인"
  - order: 8
    path: /d365
    title: ":fuelpump: 다이나믹스 365"
  - order: 9
    path: /certs
    title: ":scroll: 자격증 준비"
  - order: 10
    path: /workshops
    title: ":hammer_and_wrench: 워크샵 및 부트캠프"
  links: []
  poweredBy: {}
  enabled: true
pwa:
  enabled: true
  manifest:
    icon: /assets/logo.png
    display: minimal-ui
    crossOrigin: anonymous
features:
  editOnRepo:
    editable: true
    location: 'https://github.com/fusiondevkr/blog'
    type: github
  toc:
    show: true
    depth: 5
  search:
    enabled: true
    engine: localsearch
    localSearchEngine: balance
    excerptSize: 10000
    # indexName: docs
    startComponent: input
    showStats: true
    pagination:
      enabled: true
  rss:
    enabled: false
    showIcon: true
    copyright: ''
    categories: []
    matchRegex: ^/
    outputPath: /rss.xml
  darkMode:
    enabled: true
    default: false
social:
  facebook: 'https://facebook.com/groups/fusiondevkr'
  github: 'https://github.com/fusiondevkr'
  twitter: 'https://twitter.com/fusiondevkr'
  youtube: 'https://youtube.com/channel/UCak8-7QciP6IUgIBBGRw3Vw'
search:
  enabled: true
  startComponent: input
  placeholder: Search...
  pagination:
    enabled: true
